linters:
    disable-all: true
    enable:
        - bidichk
        - decorder
        - dupl
        - durationcheck
        - errcheck
        - errchkjson
        - errname
        - errorlint
        - exhaustive
        - exportloopref
        - forbidigo
        - gocritic
        - godot
        - gofumpt
        - gosec
        - gosimple
        - govet
        - ineffassign
        - makezero
        - misspell
        - nakedret
        - paralleltest
        - prealloc
        - predeclared
        - revive
        - staticcheck
        - tenv
        - testpackage
        - thelper
        - tparallel
        - typecheck
        - unused
        - whitespace
        - wrapcheck

linters-settings:
    exhaustive:
        default-signifies-exhaustive: true

    forbidigo:
        forbid:
            - '^path\..*(# use filepath package for Windows support)?'

    gocritic:
        enabled-checks:
            # START DEFAULTS
            - appendAssign
            - argOrder
            - assignOp
            - badCall
            - badCond
            - captLocal
            - caseOrder
            - codegenComment
            - commentFormatting
            - defaultCaseOrder
            - deprecatedComment
            - dupArg
            - dupBranchBody
            - dupCase
            - dupSubExpr
            - elseif
            - exitAfterDefer
            - flagDeref
            - flagName
            - ifElseChain
            - mapKey
            - newDeref
            - offBy1
            - regexpMust
            - singleCaseSwitch
            - sloppyLen
            - sloppyTypeAssert
            - switchTrue
            - typeSwitchVar
            - underef
            - unlambda
            - unslice
            - valSwap
            - wrapperFunc
            # START OTHERS STYLE
            - deferUnlambda
            - emptyStringTest
            - nestingReduce
            - preferFilepathJoin
            - stringConcatSimplify
            - typeDefFirst
            - unnamedResult
            - whyNoLint
            - yodaStyleExpr
            # START OTHERS PERFORMANCE
            - appendCombine
            - equalFold
            - hugeParam
            - indexAlloc
            - preferDecodeRune
            - preferFprint
            - preferStringWriter
            - preferWriteByte
            - rangeExprCopy
            - rangeValCopy
            - sliceClear
            - stringXbytes

    gosimple:
        checks: ["all"]
    makezero:
        always: true
    nakedret:
        max-func-lines: 1
    revive:
        rules:
          # START DEFAULTS
          #
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#blank-imports
          - disabled: false
            name: blank-imports
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#context-as-argument
          - disabled: false
            name: context-as-argument
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#context-keys-type
          - disabled: false
            name: context-keys-type
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#dot-imports
          - disabled: false
            name: dot-imports
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-return
          - disabled: false
            name: error-return
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-strings
          - disabled: false
            name: error-strings
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#error-naming
          - disabled: false
            name: error-naming
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported
          - disabled: false
            name: exported
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#if-return
          - disabled: false
            name: if-return
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#increment-decrement
          - disabled: false
            name: increment-decrement
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-naming
          - disabled: false
            name: var-naming
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#var-declaration
          - disabled: false
            name: var-declaration
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#package-comments
          - disabled: false
            name: package-comments
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#range
          - disabled: false
            name: range
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#range
          - disabled: false
            name: range
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#receiver-naming
          - disabled: false
            name: receiver-naming
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#time-naming
          - disabled: false
            name: time-naming
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unexported-return
          - disabled: false
            name: unexported-return
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#indent-error-flow
          - disabled: false
            name: indent-error-flow
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#errorf
          - disabled: false
            name: errorf
            severity: warning

          # START CUSTOM
          #
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#atomic
          - disabled: false
            name: atomic
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#bool-literal-in-expr
          - disabled: false
            name: bool-literal-in-expr
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#defer
          - disabled: false
            name: defer
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#early-return
          - disabled: false
            name: early-return
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#time-equal
          - disabled: false
            name: time-equal
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unhandled-error
          - disabled: false
            name: unhandled-error
            severity: warning
          # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#use-any
          - disabled: false
            name: use-any
            severity: warning
    wrapcheck:
        ignoreSigs:
          - .Errorf(
          - errors.New(
          - errors.Unwrap(
          - .Wrap(
          - .Wrapf(
          - .WithMessage(
          - .WithMessagef(
          - .WithStack(
          - jsonrpc2.NewError(
          - lsperrors.ErrRequestFailed
run:
    tests: true
