# All requirements used in these tasks:
#
# Only works on unix based shells.
#
# - go (1.20+)
# - richgo
# - golangci-lint
# - stringer (https://pkg.go.dev/golang.org/x/tools/cmd/stringer)

version: '3'

tasks:
    build:
        deps: [generate]
        cmds:
            - go build -o elephp cmd/elephp/main.go
        sources:
            - cmd/**/*
            - internal/**/*
            - pkg/**/*
            - third_party/phpstorm-stubs/**/*
            - go.mod
            - go.sum
        generates:
            - elephp

    test:
        deps: [generate]
        cmds:
            - richgo test ./... -shuffle=on -race -cover -timeout=60s -tags what

    lint:
        deps: [generate]
        cmds:
            - golangci-lint run --timeout=60s

    check:
        deps: [test, lint]

    generate:
        run: once
        cmds:
            - go generate ./...
