// Code generated by "stringer -type fixerExitCode"; DO NOT EDIT.

package phpcs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ok-0]
	_ = x[GeneralErr-1]
	_ = x[InvalidSyntax-4]
	_ = x[NeedsFixing-8]
	_ = x[AppConfigErr-16]
	_ = x[FixerConfigErr-32]
	_ = x[PHPException-64]
}

const (
	_fixerExitCode_name_0 = "OkGeneralErr"
	_fixerExitCode_name_1 = "InvalidSyntax"
	_fixerExitCode_name_2 = "NeedsFixing"
	_fixerExitCode_name_3 = "AppConfigErr"
	_fixerExitCode_name_4 = "FixerConfigErr"
	_fixerExitCode_name_5 = "PHPException"
)

var (
	_fixerExitCode_index_0 = [...]uint8{0, 2, 12}
)

func (i fixerExitCode) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _fixerExitCode_name_0[_fixerExitCode_index_0[i]:_fixerExitCode_index_0[i+1]]
	case i == 4:
		return _fixerExitCode_name_1
	case i == 8:
		return _fixerExitCode_name_2
	case i == 16:
		return _fixerExitCode_name_3
	case i == 32:
		return _fixerExitCode_name_4
	case i == 64:
		return _fixerExitCode_name_5
	default:
		return "fixerExitCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
