// Code generated by "stringer -type=CompletionAction"; DO NOT EDIT.

package project

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[NamingFunction-1]
	_ = x[NamingClassLike-2]
	_ = x[NamingNamespace-3]
	_ = x[StartingVariable-4]
	_ = x[Variable-5]
	_ = x[ObjectOp-6]
	_ = x[StaticOp-7]
	_ = x[Implements-8]
	_ = x[Extends-9]
	_ = x[Use-10]
	_ = x[AddingFile-11]
	_ = x[Newing-12]
	_ = x[Name-13]
	_ = x[NameRelative-14]
	_ = x[NameFullyQualified-15]
}

const _CompletionAction_name = "NoneNamingFunctionNamingClassLikeNamingNamespaceStartingVariableVariableObjectOpStaticOpImplementsExtendsUseAddingFileNewingNameNameRelativeNameFullyQualified"

var _CompletionAction_index = [...]uint8{0, 4, 18, 33, 48, 64, 72, 80, 88, 98, 105, 108, 118, 124, 128, 140, 158}

func (i CompletionAction) String() string {
	if i < 0 || i >= CompletionAction(len(_CompletionAction_index)-1) {
		return "CompletionAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CompletionAction_name[_CompletionAction_index[i]:_CompletionAction_index[i+1]]
}
