name: Go test

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - '**/*.go'
      - 'third-party'
      - '.github/workflows/go-test.yml'

  pull_request:
    paths:
      - '**/*.go'
      - 'third-party'
      - '.github/workflows/go-test.yml'

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1.17'

    - name: Set up Go
      id: set-up-go
      uses: actions/setup-go@v4
      with:
        check-latest: true
        cache: true
        go-version-file: go.mod

    - name: Get gobin
      id: get-gobin
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          echo ::set-output name=gobin::$(go env GOPATH)\\bin
        else
          echo ::set-output name=gobin::$(go env GOPATH)/bin
        fi
      shell: bash

    - name: Install task
      run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

    - name: Cache richgo
      uses: actions/cache@v3
      id: cache-richgo
      with:
        path: ${{ steps.get-gobin.outputs.gobin }}
        key: ${{ runner.os }}-go-test-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-test-

    - name: Install richgo
      if: ${{ steps.cache-richgo.outputs.cache-hit != 'true' }}
      run: go install github.com/kyoh86/richgo@latest

    - name: Install box
      run: composer global require humbug/box

    - name: Test
      run: task test
      env:
        RICHGO_FORCE_COLOR: 1
        CI: true
