name: Go test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        check-latest: true
        cache: true
        go-version-file: go.mod

    - name: Install richgo
      run: go install github.com/kyoh86/richgo@v0.3.10

    - name: Test
      run: richgo test -cover -race -shuffle=on -timeout=60s -v -tags what ./...
      env:
        RICHGO_FORCE_COLOR: 1
        CI: true
