name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - '**/*.go'
      - 'third-party/unsafenil'
      - '.github/workflows/golangci-lint.yml'

  pull_request:
    paths:
      - '**/*.go'
      - 'third-party/unsafenil'
      - '.github/workflows/golangci-lint.yml'

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-go@v4
        id: set-up-go
        with:
          go-version-file: go.mod
          check-latest: true
          cache: false # Caching is done by the lint action.

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=60s
