name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-go@v3
        id: set-up-go
        with:
          go-version: 1.19
          cache: true

      # TODO: cache this.
      - name: Build unsafenil
        run: go build -o ../../unsafenil.so -buildmode=plugin plugin/unsafenil.go
        working-directory: ./third_party/unsafenil


      # In order to use unsafenil, we need to build from source so CGO is used.
      # See https://github.com/golangci/golangci-lint-action/issues/540
      # See https://github.com/golangci/golangci-lint/issues/1276
      - name: Install golangci-lint
        if: ${{ steps.set-up-go.outputs.cache-hit != 'true' }}
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Add go binaries to path
        run: echo $(go env GOPATH)/bin >> $GITHUB_PATH

      - name: Lint
        run: golangci-lint run --timeout 5m

